// Generated by tools/generate-car-images.py from the unchanged original images.
export interface CarImageVariant { src: string; width: number; height: number }
export interface CarImageMetadata { width: number; height: number; variants: CarImageVariant[] }
export const optimizedCarImages: Record<string, CarImageMetadata> = {
  "/car-images/Dolphin-mini.png": {
    "width": 3235,
    "height": 1910,
    "variants": [
      {
        "src": "/car-images/optimized/Dolphin-mini.png-320.webp",
        "width": 320,
        "height": 189
      },
      {
        "src": "/car-images/optimized/Dolphin-mini.png-640.webp",
        "width": 640,
        "height": 378
      },
      {
        "src": "/car-images/optimized/Dolphin-mini.png-960.webp",
        "width": 960,
        "height": 567
      },
      {
        "src": "/car-images/optimized/Dolphin-mini.png-1280.webp",
        "width": 1280,
        "height": 756
      }
    ]
  },
  "/car-images/ariya.jpg": {
    "width": 960,
    "height": 566,
    "variants": [
      {
        "src": "/car-images/optimized/ariya.jpg-320.webp",
        "width": 320,
        "height": 189
      },
      {
        "src": "/car-images/optimized/ariya.jpg-640.webp",
        "width": 640,
        "height": 377
      },
      {
        "src": "/car-images/optimized/ariya.jpg-960.webp",
        "width": 960,
        "height": 566
      }
    ]
  },
  "/car-images/audi-a6-etron.png": {
    "width": 1440,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/audi-a6-etron.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  },
  "/car-images/audi-q6-sportback.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/audi-sq6-sportback.png": {
    "width": 1440,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  },
  "/car-images/blazer-ev.jpg": {
    "width": 960,
    "height": 576,
    "variants": [
      {
        "src": "/car-images/optimized/blazer-ev.jpg-320.webp",
        "width": 320,
        "height": 192
      },
      {
        "src": "/car-images/optimized/blazer-ev.jpg-640.webp",
        "width": 640,
        "height": 384
      },
      {
        "src": "/car-images/optimized/blazer-ev.jpg-960.webp",
        "width": 960,
        "height": 576
      }
    ]
  },
  "/car-images/byd-sealion-7.jpg": {
    "width": 1500,
    "height": 844,
    "variants": [
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/byd-yuan-plus-awd.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/cyberster.jpg": {
    "width": 960,
    "height": 755,
    "variants": [
      {
        "src": "/car-images/optimized/cyberster.jpg-320.webp",
        "width": 320,
        "height": 252
      },
      {
        "src": "/car-images/optimized/cyberster.jpg-640.webp",
        "width": 640,
        "height": 503
      },
      {
        "src": "/car-images/optimized/cyberster.jpg-960.webp",
        "width": 960,
        "height": 755
      }
    ]
  },
  "/car-images/dolphin-gs.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/dolphin-plus.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/e-2008.jpg": {
    "width": 960,
    "height": 597,
    "variants": [
      {
        "src": "/car-images/optimized/e-2008.jpg-320.webp",
        "width": 320,
        "height": 199
      },
      {
        "src": "/car-images/optimized/e-2008.jpg-640.webp",
        "width": 640,
        "height": 398
      },
      {
        "src": "/car-images/optimized/e-2008.jpg-960.webp",
        "width": 960,
        "height": 597
      }
    ]
  },
  "/car-images/e-js1.png": {
    "width": 1000,
    "height": 750,
    "variants": [
      {
        "src": "/car-images/optimized/e-js1.png-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/e-js1.png-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/e-js1.png-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/e-js1.png-1000.webp",
        "width": 1000,
        "height": 750
      }
    ]
  },
  "/car-images/e-js4.png": {
    "width": 1000,
    "height": 670,
    "variants": [
      {
        "src": "/car-images/optimized/e-js4.png-320.webp",
        "width": 320,
        "height": 214
      },
      {
        "src": "/car-images/optimized/e-js4.png-640.webp",
        "width": 640,
        "height": 429
      },
      {
        "src": "/car-images/optimized/e-js4.png-960.webp",
        "width": 960,
        "height": 643
      },
      {
        "src": "/car-images/optimized/e-js4.png-1000.webp",
        "width": 1000,
        "height": 670
      }
    ]
  },
  "/car-images/e-vitara.jpg": {
    "width": 1270,
    "height": 682,
    "variants": [
      {
        "src": "/car-images/optimized/e-vitara.jpg-320.webp",
        "width": 320,
        "height": 172
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-640.webp",
        "width": 640,
        "height": 344
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-960.webp",
        "width": 960,
        "height": 516
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-1270.webp",
        "width": 1270,
        "height": 682
      }
    ]
  },
  "/car-images/equinox-ev.jpg": {
    "width": 960,
    "height": 540,
    "variants": [
      {
        "src": "/car-images/optimized/equinox-ev.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/equinox-ev.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/equinox-ev.jpg-960.webp",
        "width": 960,
        "height": 540
      }
    ]
  },
  "/car-images/ex5-max.jpg": {
    "width": 960,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/ex5-max.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/ex5-max.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/ex5-max.jpg-960.webp",
        "width": 960,
        "height": 720
      }
    ]
  },
  "/car-images/id4.jpg": {
    "width": 960,
    "height": 554,
    "variants": [
      {
        "src": "/car-images/optimized/id4.jpg-320.webp",
        "width": 320,
        "height": 185
      },
      {
        "src": "/car-images/optimized/id4.jpg-640.webp",
        "width": 640,
        "height": 369
      },
      {
        "src": "/car-images/optimized/id4.jpg-960.webp",
        "width": 960,
        "height": 554
      }
    ]
  },
  "/car-images/idbuzz.jpg": {
    "width": 960,
    "height": 641,
    "variants": [
      {
        "src": "/car-images/optimized/idbuzz.jpg-320.webp",
        "width": 320,
        "height": 214
      },
      {
        "src": "/car-images/optimized/idbuzz.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/idbuzz.jpg-960.webp",
        "width": 960,
        "height": 641
      }
    ]
  },
  "/car-images/ix3.jpg": {
    "width": 960,
    "height": 540,
    "variants": [
      {
        "src": "/car-images/optimized/ix3.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/ix3.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/ix3.jpg-960.webp",
        "width": 960,
        "height": 540
      }
    ]
  },
  "/car-images/jac-ejv55.png": {
    "width": 609,
    "height": 365,
    "variants": [
      {
        "src": "/car-images/optimized/jac-ejv55.png-320.webp",
        "width": 320,
        "height": 192
      },
      {
        "src": "/car-images/optimized/jac-ejv55.png-609.webp",
        "width": 609,
        "height": 365
      }
    ]
  },
  "/car-images/jac-iev330p.jpg": {
    "width": 1000,
    "height": 750,
    "variants": [
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-1000.webp",
        "width": 1000,
        "height": 750
      }
    ]
  },
  "/car-images/kangoo-etech.jpg": {
    "width": 960,
    "height": 566,
    "variants": [
      {
        "src": "/car-images/optimized/kangoo-etech.jpg-320.webp",
        "width": 320,
        "height": 189
      },
      {
        "src": "/car-images/optimized/kangoo-etech.jpg-640.webp",
        "width": 640,
        "height": 377
      },
      {
        "src": "/car-images/optimized/kangoo-etech.jpg-960.webp",
        "width": 960,
        "height": 566
      }
    ]
  },
  "/car-images/leapmotor-b10.jpg": {
    "width": 960,
    "height": 710,
    "variants": [
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-320.webp",
        "width": 320,
        "height": 237
      },
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-640.webp",
        "width": 640,
        "height": 473
      },
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-960.webp",
        "width": 960,
        "height": 710
      }
    ]
  },
  "/car-images/lexus-rz-500e.jpg": {
    "width": 2560,
    "height": 1598,
    "variants": [
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-320.webp",
        "width": 320,
        "height": 200
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-640.webp",
        "width": 640,
        "height": 400
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-960.webp",
        "width": 960,
        "height": 599
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-1280.webp",
        "width": 1280,
        "height": 799
      }
    ]
  },
  "/car-images/mg4-xpower.jpg": {
    "width": 960,
    "height": 543,
    "variants": [
      {
        "src": "/car-images/optimized/mg4-xpower.jpg-320.webp",
        "width": 320,
        "height": 181
      },
      {
        "src": "/car-images/optimized/mg4-xpower.jpg-640.webp",
        "width": 640,
        "height": 362
      },
      {
        "src": "/car-images/optimized/mg4-xpower.jpg-960.webp",
        "width": 960,
        "height": 543
      }
    ]
  },
  "/car-images/mgs5-comfort.jpg": {
    "width": 960,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/mgs5-comfort.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/mgs5-comfort.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/mgs5-comfort.jpg-960.webp",
        "width": 960,
        "height": 720
      }
    ]
  },
  "/car-images/omoda-5.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/omoda-5.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/yuan-pro.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/yuan-pro.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/zeekr-7x.png": {
    "width": 1703,
    "height": 851,
    "variants": [
      {
        "src": "/car-images/optimized/zeekr-7x.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  }
};
