// Generated by tools/generate-car-images.py from the unchanged original images.
export interface CarImageVariant { src: string; width: number; height: number }
export interface CarImageMetadata { width: number; height: number; variants: CarImageVariant[] }
export const optimizedCarImages: Record<string, CarImageMetadata> = {
  "/car-images/ariya.jpg": {
    "width": 960,
    "height": 566,
    "variants": [
      {
        "src": "/car-images/optimized/ariya.jpg-320.webp",
        "width": 320,
        "height": 189
      },
      {
        "src": "/car-images/optimized/ariya.jpg-640.webp",
        "width": 640,
        "height": 377
      },
      {
        "src": "/car-images/optimized/ariya.jpg-960.webp",
        "width": 960,
        "height": 566
      }
    ]
  },
  "/car-images/audi-a6-etron.png": {
    "width": 1440,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/audi-a6-etron.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  },
  "/car-images/audi-q6-sportback.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/audi-sq6-sportback.png": {
    "width": 1440,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  },
  "/car-images/blazer-ev.jpg": {
    "width": 960,
    "height": 576,
    "variants": [
      {
        "src": "/car-images/optimized/blazer-ev.jpg-320.webp",
        "width": 320,
        "height": 192
      },
      {
        "src": "/car-images/optimized/blazer-ev.jpg-640.webp",
        "width": 640,
        "height": 384
      },
      {
        "src": "/car-images/optimized/blazer-ev.jpg-960.webp",
        "width": 960,
        "height": 576
      }
    ]
  },
  "/car-images/bmw-330e.jpg": {
    "width": 2250,
    "height": 1500,
    "variants": [
      {
        "src": "/car-images/optimized/bmw-330e.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/bmw-330e.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/bmw-330e.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/bmw-330e.jpg-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/byd-atto-2.jpg": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "src": "/car-images/optimized/byd-atto-2.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/byd-atto-2.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/byd-atto-2.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/byd-atto-2.jpg-1280.webp",
        "width": 1280,
        "height": 854
      }
    ]
  },
  "/car-images/byd-sealion-7.jpg": {
    "width": 1500,
    "height": 844,
    "variants": [
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/byd-shark.jpg": {
    "width": 5000,
    "height": 2813,
    "variants": [
      {
        "src": "/car-images/optimized/byd-shark.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-shark.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-shark.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-shark.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/byd-song-plus.webp": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/byd-song-plus.webp-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-song-plus.webp-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-song-plus.webp-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-song-plus.webp-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/byd-song-pro-flex.webp": {
    "width": 2880,
    "height": 1660,
    "variants": [
      {
        "src": "/car-images/optimized/byd-song-pro-flex.webp-320.webp",
        "width": 320,
        "height": 184
      },
      {
        "src": "/car-images/optimized/byd-song-pro-flex.webp-640.webp",
        "width": 640,
        "height": 369
      },
      {
        "src": "/car-images/optimized/byd-song-pro-flex.webp-960.webp",
        "width": 960,
        "height": 553
      },
      {
        "src": "/car-images/optimized/byd-song-pro-flex.webp-1280.webp",
        "width": 1280,
        "height": 738
      }
    ]
  },
  "/car-images/byd-yuan-plus-awd.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/caoachery-tiggo7-phev.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/caoachery-tiggo7-phev.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo7-phev.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo7-phev.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo7-phev.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/caoachery-tiggo8-phev.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/caoachery-tiggo8-phev.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo8-phev.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo8-phev.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo8-phev.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/captiva-ev.jpg": {
    "width": 1500,
    "height": 1000,
    "variants": [
      {
        "src": "/car-images/optimized/captiva-ev.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/captiva-ev.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/captiva-ev.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/captiva-ev.jpg-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/cayenne-ev.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/cayenne-ev.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/cayenne-ev.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/cayenne-ev.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/cayenne-ev.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/dolphin-gs.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/dolphin-mini.png": {
    "width": 3235,
    "height": 1910,
    "variants": [
      {
        "src": "/car-images/optimized/dolphin-mini.png-320.webp",
        "width": 320,
        "height": 189
      },
      {
        "src": "/car-images/optimized/dolphin-mini.png-640.webp",
        "width": 640,
        "height": 378
      },
      {
        "src": "/car-images/optimized/dolphin-mini.png-960.webp",
        "width": 960,
        "height": 567
      },
      {
        "src": "/car-images/optimized/dolphin-mini.png-1280.webp",
        "width": 1280,
        "height": 756
      }
    ]
  },
  "/car-images/dolphin-plus.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/e-2008.jpg": {
    "width": 960,
    "height": 597,
    "variants": [
      {
        "src": "/car-images/optimized/e-2008.jpg-320.webp",
        "width": 320,
        "height": 199
      },
      {
        "src": "/car-images/optimized/e-2008.jpg-640.webp",
        "width": 640,
        "height": 398
      },
      {
        "src": "/car-images/optimized/e-2008.jpg-960.webp",
        "width": 960,
        "height": 597
      }
    ]
  },
  "/car-images/e-js1.png": {
    "width": 1000,
    "height": 750,
    "variants": [
      {
        "src": "/car-images/optimized/e-js1.png-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/e-js1.png-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/e-js1.png-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/e-js1.png-1000.webp",
        "width": 1000,
        "height": 750
      }
    ]
  },
  "/car-images/e-js4.png": {
    "width": 1000,
    "height": 670,
    "variants": [
      {
        "src": "/car-images/optimized/e-js4.png-320.webp",
        "width": 320,
        "height": 214
      },
      {
        "src": "/car-images/optimized/e-js4.png-640.webp",
        "width": 640,
        "height": 429
      },
      {
        "src": "/car-images/optimized/e-js4.png-960.webp",
        "width": 960,
        "height": 643
      },
      {
        "src": "/car-images/optimized/e-js4.png-1000.webp",
        "width": 1000,
        "height": 670
      }
    ]
  },
  "/car-images/e-vitara.jpg": {
    "width": 1270,
    "height": 682,
    "variants": [
      {
        "src": "/car-images/optimized/e-vitara.jpg-320.webp",
        "width": 320,
        "height": 172
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-640.webp",
        "width": 640,
        "height": 344
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-960.webp",
        "width": 960,
        "height": 516
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-1270.webp",
        "width": 1270,
        "height": 682
      }
    ]
  },
  "/car-images/equinox-ev.jpg": {
    "width": 960,
    "height": 540,
    "variants": [
      {
        "src": "/car-images/optimized/equinox-ev.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/equinox-ev.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/equinox-ev.jpg-960.webp",
        "width": 960,
        "height": 540
      }
    ]
  },
  "/car-images/ex5-max.jpg": {
    "width": 960,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/ex5-max.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/ex5-max.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/ex5-max.jpg-960.webp",
        "width": 960,
        "height": 720
      }
    ]
  },
  "/car-images/farizon-sv.webp": {
    "width": 2880,
    "height": 1366,
    "variants": [
      {
        "src": "/car-images/optimized/farizon-sv.webp-320.webp",
        "width": 320,
        "height": 152
      },
      {
        "src": "/car-images/optimized/farizon-sv.webp-640.webp",
        "width": 640,
        "height": 304
      },
      {
        "src": "/car-images/optimized/farizon-sv.webp-960.webp",
        "width": 960,
        "height": 455
      },
      {
        "src": "/car-images/optimized/farizon-sv.webp-1280.webp",
        "width": 1280,
        "height": 607
      }
    ]
  },
  "/car-images/foton-ewonder.jpg": {
    "width": 1722,
    "height": 1292,
    "variants": [
      {
        "src": "/car-images/optimized/foton-ewonder.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/foton-ewonder.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/foton-ewonder.jpg-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/foton-ewonder.jpg-1280.webp",
        "width": 1280,
        "height": 960
      }
    ]
  },
  "/car-images/gac-aion-ut-elite.jpg": {
    "width": 2880,
    "height": 1913,
    "variants": [
      {
        "src": "/car-images/optimized/gac-aion-ut-elite.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/gac-aion-ut-elite.jpg-640.webp",
        "width": 640,
        "height": 425
      },
      {
        "src": "/car-images/optimized/gac-aion-ut-elite.jpg-960.webp",
        "width": 960,
        "height": 638
      },
      {
        "src": "/car-images/optimized/gac-aion-ut-elite.jpg-1280.webp",
        "width": 1280,
        "height": 850
      }
    ]
  },
  "/car-images/geely-ex5-emi.jpg": {
    "width": 5000,
    "height": 3335,
    "variants": [
      {
        "src": "/car-images/optimized/geely-ex5-emi.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/geely-ex5-emi.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/geely-ex5-emi.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/geely-ex5-emi.jpg-1280.webp",
        "width": 1280,
        "height": 854
      }
    ]
  },
  "/car-images/gwm-haval-h6-gt.webp": {
    "width": 2280,
    "height": 1440,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-haval-h6-gt.webp-320.webp",
        "width": 320,
        "height": 202
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-gt.webp-640.webp",
        "width": 640,
        "height": 404
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-gt.webp-960.webp",
        "width": 960,
        "height": 606
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-gt.webp-1280.webp",
        "width": 1280,
        "height": 808
      }
    ]
  },
  "/car-images/gwm-haval-h6-hev-one.webp": {
    "width": 1448,
    "height": 1086,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-haval-h6-hev-one.webp-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-hev-one.webp-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-hev-one.webp-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-hev-one.webp-1280.webp",
        "width": 1280,
        "height": 960
      }
    ]
  },
  "/car-images/gwm-haval-h6-phev19.webp": {
    "width": 2400,
    "height": 1600,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev19.webp-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev19.webp-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev19.webp-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev19.webp-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/gwm-haval-h6-phev35.webp": {
    "width": 2880,
    "height": 1920,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev35.webp-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev35.webp-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev35.webp-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev35.webp-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/gwm-ora-skin-bev58.jpg": {
    "width": 2880,
    "height": 1921,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-ora-skin-bev58.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/gwm-ora-skin-bev58.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/gwm-ora-skin-bev58.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/gwm-ora-skin-bev58.jpg-1280.webp",
        "width": 1280,
        "height": 854
      }
    ]
  },
  "/car-images/gwm-wey-07.webp": {
    "width": 2880,
    "height": 1758,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-wey-07.webp-320.webp",
        "width": 320,
        "height": 195
      },
      {
        "src": "/car-images/optimized/gwm-wey-07.webp-640.webp",
        "width": 640,
        "height": 391
      },
      {
        "src": "/car-images/optimized/gwm-wey-07.webp-960.webp",
        "width": 960,
        "height": 586
      },
      {
        "src": "/car-images/optimized/gwm-wey-07.webp-1280.webp",
        "width": 1280,
        "height": 781
      }
    ]
  },
  "/car-images/id4.jpg": {
    "width": 960,
    "height": 554,
    "variants": [
      {
        "src": "/car-images/optimized/id4.jpg-320.webp",
        "width": 320,
        "height": 185
      },
      {
        "src": "/car-images/optimized/id4.jpg-640.webp",
        "width": 640,
        "height": 369
      },
      {
        "src": "/car-images/optimized/id4.jpg-960.webp",
        "width": 960,
        "height": 554
      }
    ]
  },
  "/car-images/idbuzz.jpg": {
    "width": 960,
    "height": 641,
    "variants": [
      {
        "src": "/car-images/optimized/idbuzz.jpg-320.webp",
        "width": 320,
        "height": 214
      },
      {
        "src": "/car-images/optimized/idbuzz.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/idbuzz.jpg-960.webp",
        "width": 960,
        "height": 641
      }
    ]
  },
  "/car-images/ix3.jpg": {
    "width": 960,
    "height": 540,
    "variants": [
      {
        "src": "/car-images/optimized/ix3.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/ix3.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/ix3.jpg-960.webp",
        "width": 960,
        "height": 540
      }
    ]
  },
  "/car-images/jac-ej7.jpg": {
    "width": 2560,
    "height": 1440,
    "variants": [
      {
        "src": "/car-images/optimized/jac-ej7.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/jac-ej7.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/jac-ej7.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/jac-ej7.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/jac-ejv55.webp": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/jac-ejv55.webp-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/jac-ejv55.webp-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/jac-ejv55.webp-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/jac-ejv55.webp-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/jac-iev330p.jpg": {
    "width": 1000,
    "height": 750,
    "variants": [
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-1000.webp",
        "width": 1000,
        "height": 750
      }
    ]
  },
  "/car-images/leapmotor-b10.jpg": {
    "width": 960,
    "height": 710,
    "variants": [
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-320.webp",
        "width": 320,
        "height": 237
      },
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-640.webp",
        "width": 640,
        "height": 473
      },
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-960.webp",
        "width": 960,
        "height": 710
      }
    ]
  },
  "/car-images/leapmotor-c10-reev.webp": {
    "width": 720,
    "height": 515,
    "variants": [
      {
        "src": "/car-images/optimized/leapmotor-c10-reev.webp-320.webp",
        "width": 320,
        "height": 229
      },
      {
        "src": "/car-images/optimized/leapmotor-c10-reev.webp-640.webp",
        "width": 640,
        "height": 458
      },
      {
        "src": "/car-images/optimized/leapmotor-c10-reev.webp-720.webp",
        "width": 720,
        "height": 515
      }
    ]
  },
  "/car-images/lexus-nx-350h.jpg": {
    "width": 2880,
    "height": 1924,
    "variants": [
      {
        "src": "/car-images/optimized/lexus-nx-350h.jpg-320.webp",
        "width": 320,
        "height": 214
      },
      {
        "src": "/car-images/optimized/lexus-nx-350h.jpg-640.webp",
        "width": 640,
        "height": 428
      },
      {
        "src": "/car-images/optimized/lexus-nx-350h.jpg-960.webp",
        "width": 960,
        "height": 641
      },
      {
        "src": "/car-images/optimized/lexus-nx-350h.jpg-1280.webp",
        "width": 1280,
        "height": 855
      }
    ]
  },
  "/car-images/lexus-nx-450h-plus.jpg": {
    "width": 2880,
    "height": 1920,
    "variants": [
      {
        "src": "/car-images/optimized/lexus-nx-450h-plus.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/lexus-nx-450h-plus.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/lexus-nx-450h-plus.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/lexus-nx-450h-plus.jpg-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/lexus-rx-450h-plus.jpg": {
    "width": 2880,
    "height": 1921,
    "variants": [
      {
        "src": "/car-images/optimized/lexus-rx-450h-plus.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/lexus-rx-450h-plus.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/lexus-rx-450h-plus.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/lexus-rx-450h-plus.jpg-1280.webp",
        "width": 1280,
        "height": 854
      }
    ]
  },
  "/car-images/lexus-rx-500h.jpg": {
    "width": 2560,
    "height": 1707,
    "variants": [
      {
        "src": "/car-images/optimized/lexus-rx-500h.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/lexus-rx-500h.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/lexus-rx-500h.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/lexus-rx-500h.jpg-1280.webp",
        "width": 1280,
        "height": 854
      }
    ]
  },
  "/car-images/lexus-rz-500e.jpg": {
    "width": 2560,
    "height": 1598,
    "variants": [
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-320.webp",
        "width": 320,
        "height": 200
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-640.webp",
        "width": 640,
        "height": 400
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-960.webp",
        "width": 960,
        "height": 599
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-1280.webp",
        "width": 1280,
        "height": 799
      }
    ]
  },
  "/car-images/mercedes-esprinter.jpg": {
    "width": 1800,
    "height": 1200,
    "variants": [
      {
        "src": "/car-images/optimized/mercedes-esprinter.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/mercedes-esprinter.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/mercedes-esprinter.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/mercedes-esprinter.jpg-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/mini-jcw-e.jpg": {
    "width": 2250,
    "height": 1500,
    "variants": [
      {
        "src": "/car-images/optimized/mini-jcw-e.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/mini-jcw-e.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/mini-jcw-e.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/mini-jcw-e.jpg-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/mitsubishi-outlander-phev.webp": {
    "width": 2880,
    "height": 1607,
    "variants": [
      {
        "src": "/car-images/optimized/mitsubishi-outlander-phev.webp-320.webp",
        "width": 320,
        "height": 179
      },
      {
        "src": "/car-images/optimized/mitsubishi-outlander-phev.webp-640.webp",
        "width": 640,
        "height": 357
      },
      {
        "src": "/car-images/optimized/mitsubishi-outlander-phev.webp-960.webp",
        "width": 960,
        "height": 536
      },
      {
        "src": "/car-images/optimized/mitsubishi-outlander-phev.webp-1280.webp",
        "width": 1280,
        "height": 714
      }
    ]
  },
  "/car-images/neta-aya.avif": {
    "width": 1600,
    "height": 794,
    "variants": [
      {
        "src": "/car-images/optimized/neta-aya.avif-320.webp",
        "width": 320,
        "height": 159
      },
      {
        "src": "/car-images/optimized/neta-aya.avif-640.webp",
        "width": 640,
        "height": 318
      },
      {
        "src": "/car-images/optimized/neta-aya.avif-960.webp",
        "width": 960,
        "height": 476
      },
      {
        "src": "/car-images/optimized/neta-aya.avif-1280.webp",
        "width": 1280,
        "height": 635
      }
    ]
  },
  "/car-images/omoda-5.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/omoda-5.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/ora-03-gt-bev63.jpg": {
    "width": 2880,
    "height": 1920,
    "variants": [
      {
        "src": "/car-images/optimized/ora-03-gt-bev63.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/ora-03-gt-bev63.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/ora-03-gt-bev63.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/ora-03-gt-bev63.jpg-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/ora-03-skin-bev48.jpg": {
    "width": 2880,
    "height": 1921,
    "variants": [
      {
        "src": "/car-images/optimized/ora-03-skin-bev48.jpg-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/ora-03-skin-bev48.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/ora-03-skin-bev48.jpg-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/ora-03-skin-bev48.jpg-1280.webp",
        "width": 1280,
        "height": 854
      }
    ]
  },
  "/car-images/ora-05.jpg": {
    "width": 2880,
    "height": 2016,
    "variants": [
      {
        "src": "/car-images/optimized/ora-05.jpg-320.webp",
        "width": 320,
        "height": 224
      },
      {
        "src": "/car-images/optimized/ora-05.jpg-640.webp",
        "width": 640,
        "height": 448
      },
      {
        "src": "/car-images/optimized/ora-05.jpg-960.webp",
        "width": 960,
        "height": 672
      },
      {
        "src": "/car-images/optimized/ora-05.jpg-1280.webp",
        "width": 1280,
        "height": 896
      }
    ]
  },
  "/car-images/porsche-cayenne-e-hybrid.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/porsche-cayenne-e-hybrid.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/porsche-cayenne-e-hybrid.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/porsche-cayenne-e-hybrid.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/porsche-cayenne-e-hybrid.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/toyota-corolla-cross-hybrid.jpg": {
    "width": 2356,
    "height": 1111,
    "variants": [
      {
        "src": "/car-images/optimized/toyota-corolla-cross-hybrid.jpg-320.webp",
        "width": 320,
        "height": 151
      },
      {
        "src": "/car-images/optimized/toyota-corolla-cross-hybrid.jpg-640.webp",
        "width": 640,
        "height": 302
      },
      {
        "src": "/car-images/optimized/toyota-corolla-cross-hybrid.jpg-960.webp",
        "width": 960,
        "height": 453
      },
      {
        "src": "/car-images/optimized/toyota-corolla-cross-hybrid.jpg-1280.webp",
        "width": 1280,
        "height": 604
      }
    ]
  },
  "/car-images/toyota-corolla-sedan-hybrid.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/toyota-corolla-sedan-hybrid.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/toyota-corolla-sedan-hybrid.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/toyota-corolla-sedan-hybrid.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/toyota-corolla-sedan-hybrid.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/volvo-ex90.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/volvo-ex90.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/volvo-ex90.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/volvo-ex90.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/volvo-ex90.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/volvo-xc60-t8.jpg": {
    "width": 4533,
    "height": 3400,
    "variants": [
      {
        "src": "/car-images/optimized/volvo-xc60-t8.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/volvo-xc60-t8.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/volvo-xc60-t8.jpg-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/volvo-xc60-t8.jpg-1280.webp",
        "width": 1280,
        "height": 960
      }
    ]
  },
  "/car-images/volvo-xc90-t8.jpg": {
    "width": 4898,
    "height": 2756,
    "variants": [
      {
        "src": "/car-images/optimized/volvo-xc90-t8.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/volvo-xc90-t8.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/volvo-xc90-t8.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/volvo-xc90-t8.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/yuan-pro.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/yuan-pro.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/zeekr-7x.png": {
    "width": 1703,
    "height": 851,
    "variants": [
      {
        "src": "/car-images/optimized/zeekr-7x.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  }
};
