// Generated by tools/generate-car-images.py from the unchanged original images.
export interface CarImageVariant { src: string; width: number; height: number }
export interface CarImageMetadata { width: number; height: number; variants: CarImageVariant[] }
export const optimizedCarImages: Record<string, CarImageMetadata> = {
  "/car-images/ariya.jpg": {
    "width": 960,
    "height": 566,
    "variants": [
      {
        "src": "/car-images/optimized/ariya.jpg-320.webp",
        "width": 320,
        "height": 189
      },
      {
        "src": "/car-images/optimized/ariya.jpg-640.webp",
        "width": 640,
        "height": 377
      },
      {
        "src": "/car-images/optimized/ariya.jpg-960.webp",
        "width": 960,
        "height": 566
      }
    ]
  },
  "/car-images/audi-a6-etron.png": {
    "width": 1440,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/audi-a6-etron.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/audi-a6-etron.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  },
  "/car-images/audi-q6-sportback.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/audi-q6-sportback.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/audi-sq6-sportback.png": {
    "width": 1440,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/audi-sq6-sportback.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  },
  "/car-images/blazer-ev.jpg": {
    "width": 960,
    "height": 576,
    "variants": [
      {
        "src": "/car-images/optimized/blazer-ev.jpg-320.webp",
        "width": 320,
        "height": 192
      },
      {
        "src": "/car-images/optimized/blazer-ev.jpg-640.webp",
        "width": 640,
        "height": 384
      },
      {
        "src": "/car-images/optimized/blazer-ev.jpg-960.webp",
        "width": 960,
        "height": 576
      }
    ]
  },
  "/car-images/byd-sealion-7.jpg": {
    "width": 1500,
    "height": 844,
    "variants": [
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-sealion-7.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/byd-shark.jpg": {
    "width": 5000,
    "height": 2813,
    "variants": [
      {
        "src": "/car-images/optimized/byd-shark.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-shark.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-shark.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-shark.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/byd-song-pro-flex.webp": {
    "width": 2880,
    "height": 1660,
    "variants": [
      {
        "src": "/car-images/optimized/byd-song-pro-flex.webp-320.webp",
        "width": 320,
        "height": 184
      },
      {
        "src": "/car-images/optimized/byd-song-pro-flex.webp-640.webp",
        "width": 640,
        "height": 369
      },
      {
        "src": "/car-images/optimized/byd-song-pro-flex.webp-960.webp",
        "width": 960,
        "height": 553
      },
      {
        "src": "/car-images/optimized/byd-song-pro-flex.webp-1280.webp",
        "width": 1280,
        "height": 738
      }
    ]
  },
  "/car-images/byd-yuan-plus-awd.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/byd-yuan-plus-awd.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/caoachery-tiggo7-phev.webp": {
    "width": 1090,
    "height": 394,
    "variants": [
      {
        "src": "/car-images/optimized/caoachery-tiggo7-phev.webp-320.webp",
        "width": 320,
        "height": 116
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo7-phev.webp-640.webp",
        "width": 640,
        "height": 231
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo7-phev.webp-960.webp",
        "width": 960,
        "height": 347
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo7-phev.webp-1090.webp",
        "width": 1090,
        "height": 394
      }
    ]
  },
  "/car-images/caoachery-tiggo8-phev.webp": {
    "width": 1090,
    "height": 394,
    "variants": [
      {
        "src": "/car-images/optimized/caoachery-tiggo8-phev.webp-320.webp",
        "width": 320,
        "height": 116
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo8-phev.webp-640.webp",
        "width": 640,
        "height": 231
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo8-phev.webp-960.webp",
        "width": 960,
        "height": 347
      },
      {
        "src": "/car-images/optimized/caoachery-tiggo8-phev.webp-1090.webp",
        "width": 1090,
        "height": 394
      }
    ]
  },
  "/car-images/cyberster.jpg": {
    "width": 960,
    "height": 755,
    "variants": [
      {
        "src": "/car-images/optimized/cyberster.jpg-320.webp",
        "width": 320,
        "height": 252
      },
      {
        "src": "/car-images/optimized/cyberster.jpg-640.webp",
        "width": 640,
        "height": 503
      },
      {
        "src": "/car-images/optimized/cyberster.jpg-960.webp",
        "width": 960,
        "height": 755
      }
    ]
  },
  "/car-images/dolphin-gs.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/dolphin-gs.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/Dolphin-mini.png": {
    "width": 3235,
    "height": 1910,
    "variants": [
      {
        "src": "/car-images/optimized/Dolphin-mini.png-320.webp",
        "width": 320,
        "height": 189
      },
      {
        "src": "/car-images/optimized/Dolphin-mini.png-640.webp",
        "width": 640,
        "height": 378
      },
      {
        "src": "/car-images/optimized/Dolphin-mini.png-960.webp",
        "width": 960,
        "height": 567
      },
      {
        "src": "/car-images/optimized/Dolphin-mini.png-1280.webp",
        "width": 1280,
        "height": 756
      }
    ]
  },
  "/car-images/dolphin-plus.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/dolphin-plus.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/e-2008.jpg": {
    "width": 960,
    "height": 597,
    "variants": [
      {
        "src": "/car-images/optimized/e-2008.jpg-320.webp",
        "width": 320,
        "height": 199
      },
      {
        "src": "/car-images/optimized/e-2008.jpg-640.webp",
        "width": 640,
        "height": 398
      },
      {
        "src": "/car-images/optimized/e-2008.jpg-960.webp",
        "width": 960,
        "height": 597
      }
    ]
  },
  "/car-images/e-js1.png": {
    "width": 1000,
    "height": 750,
    "variants": [
      {
        "src": "/car-images/optimized/e-js1.png-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/e-js1.png-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/e-js1.png-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/e-js1.png-1000.webp",
        "width": 1000,
        "height": 750
      }
    ]
  },
  "/car-images/e-js4.png": {
    "width": 1000,
    "height": 670,
    "variants": [
      {
        "src": "/car-images/optimized/e-js4.png-320.webp",
        "width": 320,
        "height": 214
      },
      {
        "src": "/car-images/optimized/e-js4.png-640.webp",
        "width": 640,
        "height": 429
      },
      {
        "src": "/car-images/optimized/e-js4.png-960.webp",
        "width": 960,
        "height": 643
      },
      {
        "src": "/car-images/optimized/e-js4.png-1000.webp",
        "width": 1000,
        "height": 670
      }
    ]
  },
  "/car-images/e-vitara.jpg": {
    "width": 1270,
    "height": 682,
    "variants": [
      {
        "src": "/car-images/optimized/e-vitara.jpg-320.webp",
        "width": 320,
        "height": 172
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-640.webp",
        "width": 640,
        "height": 344
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-960.webp",
        "width": 960,
        "height": 516
      },
      {
        "src": "/car-images/optimized/e-vitara.jpg-1270.webp",
        "width": 1270,
        "height": 682
      }
    ]
  },
  "/car-images/equinox-ev.jpg": {
    "width": 960,
    "height": 540,
    "variants": [
      {
        "src": "/car-images/optimized/equinox-ev.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/equinox-ev.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/equinox-ev.jpg-960.webp",
        "width": 960,
        "height": 540
      }
    ]
  },
  "/car-images/ex5-max.jpg": {
    "width": 960,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/ex5-max.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/ex5-max.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/ex5-max.jpg-960.webp",
        "width": 960,
        "height": 720
      }
    ]
  },
  "/car-images/gwm-haval-h6-gt.webp": {
    "width": 2280,
    "height": 1440,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-haval-h6-gt.webp-320.webp",
        "width": 320,
        "height": 202
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-gt.webp-640.webp",
        "width": 640,
        "height": 404
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-gt.webp-960.webp",
        "width": 960,
        "height": 606
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-gt.webp-1280.webp",
        "width": 1280,
        "height": 808
      }
    ]
  },
  "/car-images/gwm-haval-h6-hev-one.webp": {
    "width": 1448,
    "height": 1086,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-haval-h6-hev-one.webp-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-hev-one.webp-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-hev-one.webp-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-hev-one.webp-1280.webp",
        "width": 1280,
        "height": 960
      }
    ]
  },
  "/car-images/gwm-haval-h6-phev19.webp": {
    "width": 2400,
    "height": 1600,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev19.webp-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev19.webp-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev19.webp-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev19.webp-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/gwm-haval-h6-phev35.webp": {
    "width": 2880,
    "height": 1920,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev35.webp-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev35.webp-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev35.webp-960.webp",
        "width": 960,
        "height": 640
      },
      {
        "src": "/car-images/optimized/gwm-haval-h6-phev35.webp-1280.webp",
        "width": 1280,
        "height": 853
      }
    ]
  },
  "/car-images/gwm-wey-07.webp": {
    "width": 2880,
    "height": 1758,
    "variants": [
      {
        "src": "/car-images/optimized/gwm-wey-07.webp-320.webp",
        "width": 320,
        "height": 195
      },
      {
        "src": "/car-images/optimized/gwm-wey-07.webp-640.webp",
        "width": 640,
        "height": 391
      },
      {
        "src": "/car-images/optimized/gwm-wey-07.webp-960.webp",
        "width": 960,
        "height": 586
      },
      {
        "src": "/car-images/optimized/gwm-wey-07.webp-1280.webp",
        "width": 1280,
        "height": 781
      }
    ]
  },
  "/car-images/id4.jpg": {
    "width": 960,
    "height": 554,
    "variants": [
      {
        "src": "/car-images/optimized/id4.jpg-320.webp",
        "width": 320,
        "height": 185
      },
      {
        "src": "/car-images/optimized/id4.jpg-640.webp",
        "width": 640,
        "height": 369
      },
      {
        "src": "/car-images/optimized/id4.jpg-960.webp",
        "width": 960,
        "height": 554
      }
    ]
  },
  "/car-images/idbuzz.jpg": {
    "width": 960,
    "height": 641,
    "variants": [
      {
        "src": "/car-images/optimized/idbuzz.jpg-320.webp",
        "width": 320,
        "height": 214
      },
      {
        "src": "/car-images/optimized/idbuzz.jpg-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/idbuzz.jpg-960.webp",
        "width": 960,
        "height": 641
      }
    ]
  },
  "/car-images/ix3.jpg": {
    "width": 960,
    "height": 540,
    "variants": [
      {
        "src": "/car-images/optimized/ix3.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/ix3.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/ix3.jpg-960.webp",
        "width": 960,
        "height": 540
      }
    ]
  },
  "/car-images/jac-ejv55.png": {
    "width": 609,
    "height": 365,
    "variants": [
      {
        "src": "/car-images/optimized/jac-ejv55.png-320.webp",
        "width": 320,
        "height": 192
      },
      {
        "src": "/car-images/optimized/jac-ejv55.png-609.webp",
        "width": 609,
        "height": 365
      }
    ]
  },
  "/car-images/jac-iev330p.jpg": {
    "width": 1000,
    "height": 750,
    "variants": [
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/jac-iev330p.jpg-1000.webp",
        "width": 1000,
        "height": 750
      }
    ]
  },
  "/car-images/kangoo-etech.jpg": {
    "width": 960,
    "height": 566,
    "variants": [
      {
        "src": "/car-images/optimized/kangoo-etech.jpg-320.webp",
        "width": 320,
        "height": 189
      },
      {
        "src": "/car-images/optimized/kangoo-etech.jpg-640.webp",
        "width": 640,
        "height": 377
      },
      {
        "src": "/car-images/optimized/kangoo-etech.jpg-960.webp",
        "width": 960,
        "height": 566
      }
    ]
  },
  "/car-images/leapmotor-b10.jpg": {
    "width": 960,
    "height": 710,
    "variants": [
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-320.webp",
        "width": 320,
        "height": 237
      },
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-640.webp",
        "width": 640,
        "height": 473
      },
      {
        "src": "/car-images/optimized/leapmotor-b10.jpg-960.webp",
        "width": 960,
        "height": 710
      }
    ]
  },
  "/car-images/leapmotor-c10-reev.webp": {
    "width": 720,
    "height": 515,
    "variants": [
      {
        "src": "/car-images/optimized/leapmotor-c10-reev.webp-320.webp",
        "width": 320,
        "height": 229
      },
      {
        "src": "/car-images/optimized/leapmotor-c10-reev.webp-640.webp",
        "width": 640,
        "height": 458
      },
      {
        "src": "/car-images/optimized/leapmotor-c10-reev.webp-720.webp",
        "width": 720,
        "height": 515
      }
    ]
  },
  "/car-images/lexus-nx-450h-plus.png": {
    "width": 1200,
    "height": 455,
    "variants": [
      {
        "src": "/car-images/optimized/lexus-nx-450h-plus.png-320.webp",
        "width": 320,
        "height": 121
      },
      {
        "src": "/car-images/optimized/lexus-nx-450h-plus.png-640.webp",
        "width": 640,
        "height": 243
      },
      {
        "src": "/car-images/optimized/lexus-nx-450h-plus.png-960.webp",
        "width": 960,
        "height": 364
      },
      {
        "src": "/car-images/optimized/lexus-nx-450h-plus.png-1200.webp",
        "width": 1200,
        "height": 455
      }
    ]
  },
  "/car-images/lexus-rz-500e.jpg": {
    "width": 2560,
    "height": 1598,
    "variants": [
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-320.webp",
        "width": 320,
        "height": 200
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-640.webp",
        "width": 640,
        "height": 400
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-960.webp",
        "width": 960,
        "height": 599
      },
      {
        "src": "/car-images/optimized/lexus-rz-500e.jpg-1280.webp",
        "width": 1280,
        "height": 799
      }
    ]
  },
  "/car-images/mg4-xpower.jpg": {
    "width": 960,
    "height": 543,
    "variants": [
      {
        "src": "/car-images/optimized/mg4-xpower.jpg-320.webp",
        "width": 320,
        "height": 181
      },
      {
        "src": "/car-images/optimized/mg4-xpower.jpg-640.webp",
        "width": 640,
        "height": 362
      },
      {
        "src": "/car-images/optimized/mg4-xpower.jpg-960.webp",
        "width": 960,
        "height": 543
      }
    ]
  },
  "/car-images/mgs5-comfort.jpg": {
    "width": 960,
    "height": 720,
    "variants": [
      {
        "src": "/car-images/optimized/mgs5-comfort.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/mgs5-comfort.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/mgs5-comfort.jpg-960.webp",
        "width": 960,
        "height": 720
      }
    ]
  },
  "/car-images/mitsubishi-outlander-phev.webp": {
    "width": 1080,
    "height": 521,
    "variants": [
      {
        "src": "/car-images/optimized/mitsubishi-outlander-phev.webp-320.webp",
        "width": 320,
        "height": 154
      },
      {
        "src": "/car-images/optimized/mitsubishi-outlander-phev.webp-640.webp",
        "width": 640,
        "height": 309
      },
      {
        "src": "/car-images/optimized/mitsubishi-outlander-phev.webp-960.webp",
        "width": 960,
        "height": 463
      },
      {
        "src": "/car-images/optimized/mitsubishi-outlander-phev.webp-1080.webp",
        "width": 1080,
        "height": 521
      }
    ]
  },
  "/car-images/omoda-5.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/omoda-5.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/omoda-5.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/toyota-corolla-cross-hybrid.png": {
    "width": 862,
    "height": 575,
    "variants": [
      {
        "src": "/car-images/optimized/toyota-corolla-cross-hybrid.png-320.webp",
        "width": 320,
        "height": 213
      },
      {
        "src": "/car-images/optimized/toyota-corolla-cross-hybrid.png-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/car-images/optimized/toyota-corolla-cross-hybrid.png-862.webp",
        "width": 862,
        "height": 575
      }
    ]
  },
  "/car-images/toyota-corolla-sedan-hybrid.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/car-images/optimized/toyota-corolla-sedan-hybrid.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/toyota-corolla-sedan-hybrid.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/toyota-corolla-sedan-hybrid.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/toyota-corolla-sedan-hybrid.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/volvo-xc60-t8.jpg": {
    "width": 4533,
    "height": 3400,
    "variants": [
      {
        "src": "/car-images/optimized/volvo-xc60-t8.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/volvo-xc60-t8.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/volvo-xc60-t8.jpg-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/volvo-xc60-t8.jpg-1280.webp",
        "width": 1280,
        "height": 960
      }
    ]
  },
  "/car-images/volvo-xc90-t8.jpg": {
    "width": 4533,
    "height": 3400,
    "variants": [
      {
        "src": "/car-images/optimized/volvo-xc90-t8.jpg-320.webp",
        "width": 320,
        "height": 240
      },
      {
        "src": "/car-images/optimized/volvo-xc90-t8.jpg-640.webp",
        "width": 640,
        "height": 480
      },
      {
        "src": "/car-images/optimized/volvo-xc90-t8.jpg-960.webp",
        "width": 960,
        "height": 720
      },
      {
        "src": "/car-images/optimized/volvo-xc90-t8.jpg-1280.webp",
        "width": 1280,
        "height": 960
      }
    ]
  },
  "/car-images/yuan-pro.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/car-images/optimized/yuan-pro.jpg-320.webp",
        "width": 320,
        "height": 180
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-640.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-960.webp",
        "width": 960,
        "height": 540
      },
      {
        "src": "/car-images/optimized/yuan-pro.jpg-1280.webp",
        "width": 1280,
        "height": 720
      }
    ]
  },
  "/car-images/zeekr-7x.png": {
    "width": 1703,
    "height": 851,
    "variants": [
      {
        "src": "/car-images/optimized/zeekr-7x.png-320.webp",
        "width": 320,
        "height": 160
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-960.webp",
        "width": 960,
        "height": 480
      },
      {
        "src": "/car-images/optimized/zeekr-7x.png-1280.webp",
        "width": 1280,
        "height": 640
      }
    ]
  }
};
