#!/usr/bin/env python3
"""Generate responsive WebP variants from existing approved catalog images.

Optional authoring dependency (not required by npm build or the deployed site):
  python3 -m venv .venv-images
  .venv-images/bin/pip install Pillow==12.3.0
  .venv-images/bin/python tools/generate-car-images.py
  .venv-images/bin/python tools/generate-car-images.py --check

Original files are retained. No crop, upscale, new photo, logo or text is added.
Generated assets and both manifests are versioned; Vitest checks their integrity.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
from pathlib import Path
import re

import PIL
from PIL import Image, ImageOps, features

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'public'
DIRECTORY = PUBLIC / 'car-images'
WIDTHS = [320, 640, 960, 1280]
THRESHOLD = 200_000
QUALITY = 82


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify without writing files')
    args = parser.parse_args()
    if not features.check('webp'):
        raise SystemExit('Pillow needs WebP support')
    output: dict[Path, bytes] = {}
    sources = []
    runtime = {}
    for path in sorted(DIRECTORY.iterdir()):
        if not path.is_file() or path.suffix.lower() not in {'.png', '.jpg', '.jpeg', '.webp', '.avif'}:
            continue
        data = path.read_bytes()
        if len(data) <= THRESHOLD:
            continue
        with Image.open(path) as original:
            image = ImageOps.exif_transpose(original)
            rgba = image.convert('RGBA')
            alpha = rgba.getchannel('A').getextrema() != (255, 255)
            image = rgba if alpha else image.convert('RGB')
            width, height = image.size
            src = '/' + path.relative_to(PUBLIC).as_posix()
            variants = []
            stem = re.sub(r'[^A-Za-z0-9_.-]+', '-', path.name)
            for size in sorted({min(w, width) for w in WIDTHS}):
                target_height = max(1, math.floor(height * size / width + 0.5))
                resized = image.resize((size, target_height), Image.Resampling.LANCZOS)
                buffer = io.BytesIO()
                resized.save(buffer, format='WEBP', quality=QUALITY, method=6, alpha_quality=100, lossless=False)
                content = buffer.getvalue()
                variant_src = f'/car-images/optimized/{stem}-{size}.webp'
                destination = PUBLIC / variant_src.lstrip('/')
                if destination in output:
                    raise SystemExit(f'Filename collision: {variant_src}')
                if len(content) >= len(data):
                    raise SystemExit(f'Variant is not smaller than original: {variant_src}')
                output[destination] = content
                variants.append({'src': variant_src, 'width': size, 'height': target_height,
                                 'bytes': len(content), 'sha256': digest(content)})
                resized.close()
            runtime[src] = {'width': width, 'height': height,
                            'variants': [{k: v[k] for k in ['src', 'width', 'height']} for v in variants]}
            sources.append({'src': src, 'width': width, 'height': height, 'alpha': alpha,
                            'bytes': len(data), 'sha256': digest(data), 'variants': variants})
            image.close()
            rgba.close()
    manifest = {'generator': {'thresholdBytes': THRESHOLD, 'widths': WIDTHS, 'quality': QUALITY,
                             'method': 6, 'alphaQuality': 100, 'pillow': PIL.__version__,
                             'webp': features.version('webp')}, 'images': sources}
    output[DIRECTORY / 'optimized' / 'manifest.json'] = (json.dumps(manifest, ensure_ascii=False, indent=2) + '\n').encode()
    types = ('// Generated by tools/generate-car-images.py from the unchanged original images.\n'
             'export interface CarImageVariant { src: string; width: number; height: number }\n'
             'export interface CarImageMetadata { width: number; height: number; variants: CarImageVariant[] }\n'
             'export const optimizedCarImages: Record<string, CarImageMetadata> = ')
    output[ROOT / 'src/utils/carImageManifest.ts'] = (types + json.dumps(runtime, ensure_ascii=False, indent=2) + ';\n').encode()
    if args.check:
        mismatches = [str(p.relative_to(ROOT)) for p, b in output.items() if not p.exists() or p.read_bytes() != b]
        if mismatches:
            raise SystemExit('Generated assets differ: ' + ', '.join(mismatches))
    else:
        for path, content in output.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    print(json.dumps({'mode': 'check' if args.check else 'write', 'sources': len(sources),
                      'variants': sum(len(s['variants']) for s in sources),
                      'originalBytes': sum(s['bytes'] for s in sources),
                      'variantBytes': sum(v['bytes'] for s in sources for v in s['variants'])}))


if __name__ == '__main__':
    main()
